# This is a basic workflow to help you get started with Actions
 
name:
  RUN PAGESPEED REPORTS
 
  # Controls when the workflow will run
on:
  # Triggers at minute 0 past every hour.
  # Helper: https://crontab.guru/
  schedule:
    - cron: "*/5 * * */6 *"
 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: GET Pagespeed Report
        run: curl '${{ vars.GOOGLE_PAGESPEED_ENDPOINT }}?url=https://www.californiaclosets.com&key=${{ secrets.GOOGLE_API_KEY }}' -o ./scans/$(date +%F_%R)-COM.json
