# This is a basic workflow to help you get started with Actions
 
name:
  RUN PAGESPEED REPORTS
 
  # Controls when the workflow will run
on:
  # Triggers at minute 0 past every hour.
  # Helper: https://crontab.guru/
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * */6 *"
 
permissions:
  contents: write
jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: GET Pagespeed Report
        run: curl '${{ vars.GOOGLE_PAGESPEED_ENDPOINT }}?url=https://www.californiaclosets.com&key=${{ secrets.GOOGLE_API_KEY }}' > $(date +%F_%R)-COM.json
      - name: Commit report
        run: |
          cd scans
          git config --global user.name 'GitHub Report Bot'
          git config --global user.email '<>'
          git commit -am "Automated report"
          git push